//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GadgeteerApp1 {
    using Gadgeteer;
    using GTM = Gadgeteer.Modules;
    
    
    public partial class Program : Gadgeteer.Program {
        
        /// <summary>The USB Client SP module using socket 2 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.USBClientSP usbClientSP;
        
        /// <summary>The LED7R module using socket 3 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.LED7R led7R;
        
        /// <summary>The IO60P16 module using socket 6 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.IO60P16 io60P16;
        
        /// <summary>The Compass module using socket 5 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Compass compass;
        
        /// <summary>The Joystick module using socket 14 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Joystick joystick;
        
        /// <summary>This property provides access to the Mainboard API. This is normally not necessary for an end user program.</summary>
        protected new static GHIElectronics.Gadgeteer.FEZHydra Mainboard {
            get {
                return ((GHIElectronics.Gadgeteer.FEZHydra)(Gadgeteer.Program.Mainboard));
            }
            set {
                Gadgeteer.Program.Mainboard = value;
            }
        }
        
        /// <summary>This method runs automatically when the device is powered, and calls ProgramStarted.</summary>
        public static void Main() {
            // Important to initialize the Mainboard first
            Program.Mainboard = new GHIElectronics.Gadgeteer.FEZHydra();
            Program p = new Program();
            p.InitializeModules();
            p.ProgramStarted();
            // Starts Dispatcher
            p.Run();
        }
        
        private void InitializeModules() {
            this.usbClientSP = new GTM.GHIElectronics.USBClientSP(2);
            this.led7R = new GTM.GHIElectronics.LED7R(3);
            this.io60P16 = new GTM.GHIElectronics.IO60P16(6);
            this.compass = new GTM.GHIElectronics.Compass(5);
            this.joystick = new GTM.GHIElectronics.Joystick(14);
        }
    }
}
